name: Push Patient Service Docker Image to Docker Hub

on:
  push:
    branches: [ main ]
    paths:
      - 'patient-service/src/**'
      - 'patient-service/pom.xml'
      - 'patient-service/Dockerfile'

  pull_request:
    types: [ closed ]
    branches: [ main ]
    paths:
      - 'patient-service/src/**'
      - 'patient-service/pom.xml'
      - 'patient-service/Dockerfile'

  workflow_dispatch:

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      # 3. Build and Test
      - name: Build with Maven
        run: mvn -B package --file patient-service/pom.xml

      # 4. Docker Hub Login
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Build Docker image
      - name: Build Docker image
        run: |
          IMAGE="bhavinm/patient-management_patient-service"
          TAG="${{ github.sha }}"
          docker build -t $IMAGE:$TAG -t $IMAGE:latest -f patient-service/Dockerfile patient-service

      # 6. Push Docker image
      - name: Push Docker image
        run: |
          IMAGE="bhavinm/patient-management_patient-service"
          TAG="${{ github.sha }}"
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest
